# Generated by Django 4.0.4 on 2022-05-04 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plataforma',
            name='numerodecliente',
            field=models.IntegerField(default=0),
        ),
    ]
