# Generated by Django 4.0.4 on 2022-05-04 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_plataforma_numerodecliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plataforma',
            name='numerodecliente',
            field=models.IntegerField(),
        ),
    ]
